<?php
 class_exists('m4is_emz57o') || die(); final 
class m4is__5ub0n { static 
function m4is_a6x52r() : self { static $m4is_jprj8 = false; return $m4is_jprj8 ? $m4is_jprj8 : $m4is_jprj8 = new self; } private 
function __construct() { $this->m4is_ap508(); if ( is_admin() ) { include __DIR__ . '/admin.php'; m4is__ry9::m4is_a6x52r(); } } private 
function m4is_ap508() { add_action( 'lifterlms_course_completed', [$this, 'm4is_oy1rbo'], 5, 2 ); add_action( 'lifterlms_quiz_completed', [$this, 'm4is_qm1vb'], 5, 2 ); add_action( 'llms_trigger_lesson_completion', [$this, 'm4is_xu74'], 5, 2 ); add_action( 'llms_user_added_to_membership_level', [$this, 'm4is_fhiqgl'], 5, 2 ); add_action( 'llms_user_removed_from_membership_level', [$this, 'm4is_lu0j4'], 5, 2 ); add_action( 'memberium/session/updated', [$this, 'm4is_sivbp'], 10, 2); add_filter( 'memberium/lms/course_category', [$this, 'm4is_hhyk']); add_filter( 'memberium/lms/course_tag', [$this, 'm4is_n0s4i']); add_filter( 'memberium/lms/course_type', [$this, 'm4is_x2lz']); add_filter( 'memberium/lms/course/item/data', [$this, 'm4is_mirntk'], 10, 2); }  
function m4is_fhiqgl( $m4is_q4c_xa, $m4is_sdob0 ) { $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); if ( $m4is_aicfp ) { $m4is_ti8od = get_post_meta( $m4is_sdob0 ); } }  
function m4is_lu0j4( $m4is_q4c_xa, $m4is_sdob0 ) { $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); if ( $m4is_aicfp ) { $m4is_ti8od = get_post_meta( $m4is_sdob0 ); } } 
function m4is_oy1rbo($m4is_q4c_xa, $m4is_u6ixo) { $m4is_ti8od = get_post_meta( $m4is_u6ixo ); $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); if ( $m4is_aicfp ) { if ( ! empty( $m4is_ti8od['_is4wp_learndash_goals'][0] ) ) { memberium_app()->m4is_rctzo( $m4is_ti8od['_is4wp_learndash_goals'][0], $m4is_aicfp ); } if ( ! empty( $m4is_ti8od['_is4wp_learndash_tags'][0] ) ) { memberium_app()->m4is__mkz( $m4is_ti8od['_is4wp_learndash_tags'][0], $m4is_aicfp ); } if ( ! empty( $m4is_ti8od['_is4wp_learndash_actions'][0] ) ) { memberium_app()->m4is_evrbh( $m4is_ti8od['_is4wp_learndash_actions'][0], $m4is_aicfp ); } if ( ! empty( $m4is_ti8od['_is4wp_learndash_shortcodes'][0] ) ) { $result = doShortcode( $m4is_ti8od['_is4wp_learndash_shortcodes'][0], true ); } } do_action('memberium/lms/completion', $m4is_q4c_xa, $m4is_u6ixo); } 
function m4is_xu74( $m4is_q4c_xa, $m4is_qoed9n ) { $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); $m4is_e94dz = get_post_meta($m4is_qoed9n); if ($m4is_aicfp) { if ( ! empty( $m4is_e94dz['_is4wp_learndash_goals'][0] ) ) { memberium_app()->m4is_rctzo( $m4is_e94dz['_is4wp_learndash_goals'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_tags'][0] ) ) { memberium_app()->m4is__mkz( $m4is_e94dz['_is4wp_learndash_tags'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_actions'][0] ) ) { memberium_app()->m4is_evrbh( $m4is_e94dz['_is4wp_learndash_actions'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_shortcodes'][0] ) ) { doShortcode( $m4is_e94dz['_is4wp_learndash_shortcodes'][0], true ); } } do_action('memberium/lms/completion', $m4is_q4c_xa, $m4is_qoed9n); } 
function m4is_qm1vb( $m4is_q4c_xa, $m4is_n02q7 ) { $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); $m4is_uoj5 = $m4is_n02q7['id']; $m4is_e94dz = get_post_meta( $m4is_uoj5 ); if (! $m4is_n02q7['passed']) { return; } if (! $m4is_aicfp) { if ( ! empty( $m4is_e94dz['_is4wp_learndash_goals'][0] ) ) { memberium_app()->m4is_rctzo( $m4is_e94dz['_is4wp_learndash_goals'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_tags'][0] ) ) { memberium_app()->m4is__mkz( $m4is_e94dz['_is4wp_learndash_tags'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_actions'][0] ) ) { memberium_app()->m4is_evrbh( $m4is_e94dz['_is4wp_learndash_actions'][0], $m4is_aicfp ); } if ( ! empty( $m4is_e94dz['_is4wp_learndash_shortcodes'][0] ) ) { $result = doShortcode( $m4is_e94dz['_is4wp_learndash_shortcodes'][0], true ); } } do_action('memberium/lms/completion', $m4is_q4c_xa, $m4is_uoj5); } 
function m4is_sivbp($m4is_q4c_xa, $m4is_sxfbjo) { global $wpdb;  $m4is_f9av2 = $wpdb->posts; $m4is_zs2va = $wpdb->postmeta; $m4is_ioxk = "SELECT ID, meta_value FROM {$m4is_f9av2}, {$m4is_zs2va} WHERE post_status = 'publish' AND post_type = 'course' AND  post_id = ID AND meta_key = '_is4wp_learndash_autoenroll' AND meta_value > '' "; $m4is__jp4yb = $wpdb->get_results( $m4is_ioxk, ARRAY_A ); if ( is_array( $m4is__jp4yb ) && ! empty( $m4is__jp4yb ) ) { $m4is_zjpo = new LLMS_Student( $m4is_q4c_xa ); foreach ( $m4is__jp4yb as $m4is_pgsbl ) { $m4is_skh0p = llms_is_user_enrolled( $m4is_q4c_xa, $m4is_pgsbl['ID'] ); $m4is_ypu1m = memberium_app()->m4is_ww6ul( $m4is_pgsbl['meta_value'], $m4is_sxfbjo ); if ( $m4is_skh0p ) { if ( ! $m4is_ypu1m ) { $m4is_zjpo->unenroll( $m4is_pgsbl['ID'] ); } } else { if ( $m4is_ypu1m ) { $m4is_zjpo->enroll( $m4is_pgsbl['ID'] ); } } } } }  
function m4is_mirntk(array $m4is_j0n7, int $m4is__xysg){ if (get_post_type($m4is__xysg) !== 'course') { return $m4is_j0n7; } $m4is_q4c_xa = get_current_user_id();  $m4is_j0n7['access'] = m4is_pcys::m4is_a6x52r()->m4is_whka($m4is__xysg, $m4is_q4c_xa); if( ! $m4is_j0n7['access'] ){ $m4is_j0n7['status'] = 'locked'; return $m4is_j0n7; } $m4is_l6omu9 = new LLMS_Course( $m4is__xysg );  $m4is_skh0p = llms_is_user_enrolled( $m4is_q4c_xa, $m4is__xysg ); if( ! $m4is_skh0p ){ if( ! $m4is_l6omu9->is_enrollment_open() || ! $m4is_l6omu9->has_capacity() ){ $m4is_j0n7['access'] = 0; $m4is_j0n7['status'] = 'locked'; return $m4is_j0n7; } else{ $m4is_j0n7['status'] = 'not_enrolled'; } $m4is_j0n7['url'] = $m4is_l6omu9->get_sales_page_url(); }  if ( $m4is_l6omu9->has_prerequisite( 'course' ) && ! $m4is_l6omu9->is_prerequisite_complete( 'course' ) ){ $m4is_j0n7['access'] = 0;  $m4is_j0n7['status'] = 'locked'; return $m4is_j0n7; }  if ( $m4is_l6omu9->has_prerequisite( 'course_track' ) && ! $m4is_l6omu9->is_prerequisite_complete( 'course_track' ) ) { $m4is_j0n7['access'] = 0;  $m4is_j0n7['status'] = 'locked'; return $m4is_j0n7; } $m4is_j0n7['progress'] = $m4is_l6omu9->get_percent_complete( $m4is_q4c_xa ); return $m4is_j0n7; } 
function m4is_x2lz($m4is_dmesa) { return 'course'; } 
function m4is_hhyk($m4is_qmxu) { return 'course_cat'; } 
function m4is_n0s4i($m4is_w9feq2) { return 'course_tag'; } }
