<?php
 class_exists('m4is_emz57o') || die();  final 
class m4is_nafz { private  $m4is_nq7s = [], $m4is_aicfp = 0, $m4is_tvcm = [], $m4is_adiq = false, $m4is_tjzfa1 = 0, $m4is_ssdxa6 = [], $m4is_qw8dk = '', $m4is_xiu_ = [], $m4is_aaz9 = '', $m4is_pgsbl = [], $m4is_e2kyt = 0, $m4is_wtg_l8 = [], $m4is_ncgn = [],  $m4is_mr7hxo = '', $m4is_knsa = '', $m4is__oez2t = '', $m4is_flwmo = '', $m4is_r_2vlj = ''; static 
function m4is_burleh( array $m4is_ssdxa6 = [], array $m4is_pgsbl = [] ) : self { static $m4is_jprj8; return $m4is_jprj8 ? $m4is_jprj8 : $m4is_jprj8 = new self( $m4is_ssdxa6, $m4is_pgsbl ); } private 
function __construct( array $m4is_ssdxa6, array $m4is_pgsbl ) { ini_set( 'display_errors', 1 ); $m4is_ssdxa6 = empty( $m4is_ssdxa6 ) ? $_GET : $m4is_ssdxa6; $m4is_pgsbl = empty( $m4is_pgsbl ) ? $_POST : $m4is_pgsbl; $this->m4is_efgr75( $m4is_ssdxa6, $m4is_pgsbl ); $this->m4is_n4csyz(); $this->m4is_l8ydl(); $this->m4is_mjhbk(); $this->m4is_pp0i(); $this->m4is_zmo96(); } 
function __destruct() { $m4is_ig2l = microtime( true ) - $this->m4is_e2kyt; $m4is_fgxy = sprintf( "Completed Set Date HTTP POST.  Processing time: %0.3f seconds\n", $m4is_ig2l ); $this->m4is_xiu_[] = $m4is_fgxy; $this->m4is_xiu_ = array_filter( $this->m4is_xiu_ ); if ( $this->m4is_aaz9 && ! empty( $this->m4is_xiu_ ) ) { m4is_q1amx::m4is_rf68r( $this->m4is_aaz9, implode( "\n", $this->m4is_xiu_ ) ); } if ( $this->m4is_adiq ) { echo $m4is_fgxy; } } private 
function m4is_efgr75( array $m4is_ssdxa6, array $m4is_pgsbl ) { $this->m4is_e2kyt = isset( $_SERVER['REQUEST_TIME_FLOAT'] ) ? $_SERVER['REQUEST_TIME_FLOAT'] : microtime( true ); $this->m4is_ssdxa6 = $m4is_ssdxa6; $this->m4is_pgsbl = $m4is_pgsbl; $this->m4is_tvcm = m4is_f84s3h::m4is_cm6nr( 'Contact', false ); ksort( $this->m4is_pgsbl ); } private 
function m4is_n4csyz() { $this->m4is_nq7s = $this->m4is_pgsbl; $this->m4is_aicfp = isset( $this->m4is_nq7s['Id'] ) ? (int) $this->m4is_nq7s['Id'] : $this->m4is_aicfp; $this->m4is_adiq = isset( $this->m4is_ssdxa6['debug'] ) ? $this->m4is_y06fw( $this->m4is_ssdxa6['debug'], false ) : false; $this->m4is_tjzfa1 = empty( $this->m4is_ssdxa6['delay'] ) ? 0 : (int) $this->m4is_ssdxa6['delay']; $this->m4is_mr7hxo = empty( $this->m4is_ssdxa6['format'] ) ? 'Y-m-d\TH:i:s' : $this->m4is_ssdxa6['format']; $this->m4is_knsa = empty( $this->m4is_ssdxa6['function'] ) ? '' : str_replace( 'plus', '+', $this->m4is_ssdxa6['function'] ); $this->m4is_qw8dk = empty( $this->m4is_ssdxa6['goal'] ) ? '' : $this->m4is_ssdxa6['goal']; $this->m4is_flwmo = isset( $this->m4is_ssdxa6['source'] ) ? $this->m4is_ssdxa6['source'] : 'now'; $this->m4is_wtg_l8 = empty( $this->m4is_ssdxa6['tagids'] ) ? [] : array_filter( explode( ',', $this->m4is_ssdxa6['tagids'] ) ); $this->m4is_r_2vlj = isset( $this->m4is_ssdxa6['target'] ) ? array_filter( explode( ',', $this->m4is_ssdxa6['target'] ) ) : []; $this->m4is_aaz9 = m4is_q1amx::m4is_u4dk( $this->m4is_aicfp, 'httppost', "Set Date\n"); } private 
function m4is_l8ydl() { $m4is_fzalfr = []; $m4is_rg0su = []; if ( ! $this->m4is_aicfp ) { $m4is_fzalfr[] = "Error: No Contact ID provided"; } if ( empty( $this->m4is_flwmo ) && ! in_array( $this->m4is_flwmo, $this->m4is_tvcm ) ) { $m4is_fzalfr[] = "Error: No valid source field provided."; } foreach( $this->m4is_r_2vlj as $m4is_ap3_ => $m4is_sv3h ) { if ( ! in_array( $m4is_sv3h, $this->m4is_tvcm ) ) { $m4is_rg0su[] = sprintf( "Warning: %s is not a valid target field.", $m4is_sv3h ); unset( $this->m4is_r_2vlj[$m4is_ap3_] ); } } if ( empty( $this->m4is_r_2vlj ) ) { $m4is_fzalfr[] = "Error: No valid target fields provided."; } if ( in_array( $this->m4is_flwmo, $this->m4is_tvcm ) && ! empty( $this->m4is_nq7s[ $this->m4is_flwmo ] ) ) { $this->m4is_rhfd = $this->m4is_nq7s[ $this->m4is_flwmo ]; } $this->m4is_xiu_ = array_merge( $this->m4is_xiu_, $m4is_rg0su, $m4is_fzalfr ); if ( $this->m4is_adiq ) { printf( "%s = %s = %s\n", __LINE__, 'Contact ID', $this->m4is_aicfp ); printf( "%s = %s = %s\n", __LINE__, 'Source Field', $this->m4is_flwmo ); printf( "%s = %s = %s\n", __LINE__, 'Source Value', $this->m4is_rhfd ); printf( "%s = %s = %s\n", __LINE__, 'Function/Operation', $this->m4is_knsa ); printf( "%s = %s = %s\n", __LINE__, 'Date Format', $this->m4is_mr7hxo ); printf( "%s = %s = %s\n", __LINE__, 'Target Fields', implode( ', ', $this->m4is_r_2vlj ) ); echo empty( $m4is_rg0su ) ? '' : implode( "\n", $m4is_rg0su ) . "\n"; echo empty( $m4is_fzalfr ) ? '' : implode( "\n", $m4is_fzalfr ) . "\n"; } if ( count( $m4is_fzalfr ) ) { die(); } } private 
function m4is_mjhbk() { $this->m4is__oez2t = date( $this->m4is_mr7hxo, strtotime( $this->m4is_rhfd . $this->m4is_knsa ) ); $this->m4is_xiu_[] = sprintf( "Source = %s, Value = %s, Function = %s", $this->m4is_flwmo, $this->m4is_rhfd, $this->m4is_knsa ); $this->m4is_xiu_[] = sprintf( "Format = %s, New Date = %s, Target Fields = %s", $this->m4is_mr7hxo, $this->m4is__oez2t, implode( ', ', $this->m4is_r_2vlj ) ); if ( $this->m4is_adiq ) { printf( "%s = %s = %s\n", __LINE__, 'Destination Value', $this->m4is__oez2t ); } } private 
function m4is_pp0i() { foreach ( $this->m4is_r_2vlj as $m4is_sv3h ) { $this->m4is_ncgn[ $m4is_sv3h ] = $this->m4is__oez2t; $this->m4is_nq7s[ $m4is_sv3h ] = $this->m4is__oez2t; } if ( count( $this->m4is_ncgn ) ) { m4is_zbyh::m4is_pp0i( $this->m4is_aicfp, $this->m4is_ncgn );  memberium_app()->m4is_ba7dk( $this->m4is_nq7s ); } } private 
function m4is_zmo96() { if ( ! empty( $this->m4is_wtg_l8 ) ) { memberium_app()->m4is__mkz( $this->m4is_wtg_l8, $this->m4is_aicfp ); if ($m4is_ia_osy) { echo __LINE__, " - Added Tags: ", implode(', ', $this->m4is_wtg_l8 ), "\n"; } $this->m4is_xiu_[] = sprintf('Added Tags ', implode( ', ', $this->m4is_wtg_l8 ) ); } if ( ! empty( $this->m4is_qw8dk ) ) { $m4is_lgnh7 = explode( ':', $this->m4is_qw8dk ); $m4is__i1sg = $m4is_lgnh7[0]; $m4is_qw8dk = $m4is_lgnh7[1]; m4is_f84s3h::m4is_zox_z5( $this->m4is_aicfp, $m4is_qw8dk, $m4is__i1sg ); if ( $this->m4is_adiq ) { printf( "%d - Goal Achieved with %s\n", __LINE__, implode( ', ', $this->m4is_qw8dk ) ); } } if ( $this->m4is_adiq ) { echo __LINE__, " - Updated Contact\n"; echo __LINE__, " - Sleeping: {$this->m4is_tjzfa1} seconds\n"; } memberium_app()->m4is_l41p7r( $this->m4is_aicfp ); memberium_app()->m4is_v64c('send_http_post'); sleep( $this->m4is_tjzfa1 ); } private 
function m4is_s2u9da( $m4is_rhfd ) { return $m4is_rhfd ? 'Yes' : 'No'; } private 
function m4is_y06fw( $m4is_rhfd, bool $m4is_lphf = false ) : bool { $m4is_rhfd = strtolower( substr( trim( $m4is_rhfd ), 0, 1 ) ); return in_array( $m4is_rhfd, [ 'y', 't', '1' ] ) ? true : ( in_array( $m4is_rhfd, [ 'n', 'f', '0' ] ) ? false : $m4is_lphf ); } }
