<?php
/**
 * Copyright (c) 2022 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_emz57o') || die(); final 
class m4is_oz3r { public static 
function m4is__6hr_b() { self::m4is_b0c2(); self::m4is_c7kg(); self::m4is_t57utp(); self::m4is_ipkbym(); self::m4is_uh6k(); self::m4is_gofal(); self::m4is_kh_7m(); self::m4is_v23z(); self::m4is_jg1uw(); self::m4is_se5c(); self::m4is_ac2h(); self::m4is_lkwzs(); self::m4is__r9bv4(); self::m4is_x0ku(); self::m4is_qlqocy(); self::m4is_gj9lqo(); self::m4is_u5our(); self::m4is_nibz14(); self::m4is_gv3ay(); }  public static 
function m4is_i0n97q() { global $wpdb; $m4is__u0k = get_option(m4is_o5aoir::m4is_y40c_u() ); $m4is_nvawk6 = m4is_o5aoir::m4is_ehns($m4is__u0k); echo '<h3>License Status</h3>'; echo '<p class="indented">'; echo '<label>Valid</label>'; echo '<span>', ( (boolean) $m4is_nvawk6['valid'] ? '<strong style="color:green;">Yes</strong>' : '<strong style="color:red;">No</strong>'), '</span><br />'; echo '<label>Active</label>'; echo '<span>', ( (boolean) $m4is_nvawk6['active'] ? '<strong style="color:green;">Yes</strong>' : '<strong style="color:red;">No</strong>'), '</span><br />'; if ( (boolean) $m4is_nvawk6['trial_mode']) { echo '<label>Test Mode</label>'; echo '<span><strong style="color:red;">TEST LICENSE MODE</strong></span><br />'; } echo '<label>Next Check</label>'; echo '<span>', date('F jS, Y @ h:i:s', $m4is_nvawk6['next_check']), '</span><br />'; echo '<label>Renewal Date</label>'; echo '<span>', date('F jS, Y @ h:i:s', $m4is_nvawk6['renewal_date']), '</span><br />'; echo '</p>'; echo '<hr />'; echo '<h3>License Detail</h3>'; echo '<textarea cols="100" rows="10">'; foreach ($m4is_nvawk6 as $m4is_e3k_mi => $m4is_waxrhu) { echo ucwords(str_replace('_', ' ', $m4is_e3k_mi) ), ':  ', $m4is_waxrhu, "\n"; } echo '</textarea>'; }  public static 
function m4is_nhva_w() { $m4is_fdf0v = memberium_app()->m4is_mmdrl('memberships'); echo '<h3>Memberships</h3>'; echo '<textarea cols="100" rows="20">', json_encode($m4is_fdf0v, JSON_PRETTY_PRINT), '</textarea>'; }  public static 
function m4is_ss_c() { echo '<h3>i2SDK Beta Debug</h3>'; $m4is_wql7a2 = m4is_o5aoir::m4is__qlbej(); echo '<label>License Status</label>'; echo '<span>', (int) $m4is_wql7a2, '</span><br />'; }     private static 
function m4is_ipkbym() { echo '<h3>Object Caching</h3>'; echo '<div class="indented">'; if (wp_using_ext_object_cache() ) { $m4is_mqrtd = []; $m4is_sbkzp = get_object_vars($GLOBALS['wp_object_cache']); $m4is_mqrtd['misses'] = empty($m4is_sbkzp['cache_misses']) ? 0 : $m4is_sbkzp['cache_misses']; $m4is_mqrtd['hits'] = empty($m4is_sbkzp['cache_hits']) ? 0 : $m4is_sbkzp['cache_hits']; $m4is_mqrtd['client'] = empty($m4is_sbkzp['redis_client']) ? 'Unknown' : $m4is_sbkzp['redis_client']; if (function_exists('wp_cache_get_stats')) { $m4is_sbkzp = wp_cache_get_stats(); echo '<p>Alternate Object Cache Detected (wp_cache_get_stats)</p>';  } if (method_exists($GLOBALS['wp_object_cache'], 'getstats') ) { $m4is_sbkzp = $GLOBALS['wp_object_cache']->getStats(); echo '<p>Alternate Object Cache Detected (getStats)</p>';  } echo '<p>'; echo "<strong>Object Cache Client:</strong>  {$m4is_mqrtd['client']}<br />"; echo "<strong>Object Cache Hits:</strong>  {$m4is_mqrtd['hits']}<br />"; echo "<strong>Object Cache Misses:</strong>  {$m4is_mqrtd['misses']}</p>"; echo '</p>'; } else { echo '<p style="color:red;font-weight:bold;">Disabled</p>'; } echo '</div>'; }  private static 
function m4is_c7kg() { $m4is_fs76o2 = [ 'HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'CF-CONNECTING-IP', ]; echo '<h3>Remote IP Address</h3>'; echo '<div class="indented">'; foreach($m4is_fs76o2 as $m4is_c2vnk) { if (! empty($_SERVER[$m4is_c2vnk])) { echo $m4is_c2vnk, ' - ', $_SERVER[$m4is_c2vnk], '<br />'; } } echo '</div>'; }  private static 
function m4is_kh_7m() { global $wpdb; $m4is_po4p = get_option('memberium_tables', [] ); $m4is_dqth = []; if (is_array($m4is_po4p)) { foreach($m4is_po4p as $m4is_hs4_6) {   $m4is_ioxk = "SELECT 1 FROM `{$m4is_hs4_6}` LIMIT 1;"; $wpdb->get_var($m4is_ioxk); $m4is_rr90 = $wpdb->last_error; if ($m4is_rr90) { $m4is_dqth[] = "Table '{$m4is_hs4_6}' : <span style='font-weight:bold;color:red;'>{$m4is_rr90}</span><br />"; } } } echo '<h3>Missing Database Tables</h3>'; echo '<div class="indented">'; if (! empty($m4is_dqth)) { foreach($m4is_dqth as $m4is_bxoi) { echo $m4is_bxoi, '<br>'; } } else { echo '<p>None</p>'; } echo '</div>'; } private static 
function m4is_x0ku() { echo '<h3>wp-admin php.ini</h3>'; if (file_exists(get_home_path() . '/wp-admin/php.ini') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . '/wp-admin/php.ini'), '</textarea>'; } else { echo '<p>Not Found</p>'; } } private static 
function m4is_u5our() { $m4is_qmry = get_defined_constants(true); if (isset($m4is_qmry['user']) ) { ksort($m4is_qmry['user']); echo '<h3>Constants</h3>'; echo '<table>'; foreach($m4is_qmry['user'] as $k => $v) { echo '<tr><td>', $k, '</td><td>', $v, '</td></tr>'; } echo '</table>'; } } private static 
function m4is_je_by() { $m4is_zb9pck = '<strong style="color:red;">Unknown</strong>'; $m4is_hy7d = '/proc/cpuinfo'; if ( @is_readable( $m4is_hy7d ) ) { $m4is_zz24dx = @file( $m4is_hy7d ); if ( is_array( $m4is_zz24dx ) ) { foreach( $m4is_zz24dx as $m4is__h0w ) { if ( substr( $m4is__h0w, 0, 9 ) == 'cpu cores' ) { $m4is_zb9pck = intval( $m4is_zb9pck ) + (int) substr( $m4is__h0w, strpos( $m4is__h0w, ':' ) + 1 ); } } } } return $m4is_zb9pck; } private static 
function m4is_gj9lqo() { echo '<h3>Cron Jobs</h3>'; echo '<div class="indented">'; $m4is_g65rt9 = []; $m4is_oy9c = get_option('cron', [] ); if (count($m4is_oy9c) ) { foreach ($m4is_oy9c as $m4is_fws8ny => $m4is_icdqo) { if (is_array($m4is_icdqo) ) { foreach ($m4is_icdqo as $jobname => $details) { if (stripos($jobname, 'memberium') === 0) { $m4is_g65rt9[$jobname] = $m4is_fws8ny; } } } } } echo '<strong style="margin-left:20px;display:inline-block;width:250px;">Cron Job Name</strong><strong>Next Run Time</strong><br>'; if (! empty($m4is_g65rt9) ) { foreach ($m4is_g65rt9 as $m4is_ho0w2 => $m4is_il8u4) { echo '<span style="margin-left:20px;display:inline-block;width:250px;">', $m4is_ho0w2, '</span>', date("Y-m-d h:i:s", $m4is_il8u4), '<br>'; } } echo '</div>'; } private static 
function m4is_v23z() { echo '<h3>CURL Library Support</h3>'; echo '<div class="indented">'; if (function_exists('curl_version') ) { $m4is_r_h0jw = curl_version(); echo '<strong>Version</strong>: ', $m4is_r_h0jw['version'], '<br />'; echo '<strong>Version Number</strong>: ', $m4is_r_h0jw['version_number'], '<br />'; echo '<strong>SSL Version</strong>: ', $m4is_r_h0jw['ssl_version'], '<br />'; echo '<strong>LibZ Version</strong>: ', $m4is_r_h0jw['libz_version'], '<br />'; echo '<strong>Age</strong>: ', $m4is_r_h0jw['age'], '<br />'; } else { echo '<p style="color:red;font-weight:bold;">CURL Library Support Missing</p>'; } echo '</div>'; } private static 
function m4is_gofal() { global $wpdb; echo '<h3>MySQL Configuration</h3>'; echo '<div class="indented">'; echo '<h3>Database Storage Engines:</h3>'; $m4is_ioxk = 'SHOW STORAGE ENGINES;'; $m4is_jr7f6 = $wpdb->get_results($m4is_ioxk, ARRAY_A); echo '<table>'; echo '<tr>'; echo '<td>Engine Name</td>'; echo '<td>Support</td>'; echo '<td>Comments / Description</td>'; echo '</tr>'; foreach($m4is_jr7f6 as $m4is_n_bp6) { echo '<tr>'; echo '<td>',$m4is_n_bp6['Engine'],'</td>'; echo '<td>',$m4is_n_bp6['Support'],'</td>'; echo '<td>',$m4is_n_bp6['Comment'],'</td>'; echo '</tr>'; } echo '</table>'; echo '<h3>Cache Configuration</h3>'; $m4is_ioxk = "show variables like 'have_query_cache';"; $m4is_n_bp6 = $wpdb->get_results($m4is_ioxk); echo '<strong>', $m4is_n_bp6[0]->Variable_name, '</strong> = ', $m4is_n_bp6[0]->Value, '<br>'; $m4is_ioxk = "show variables like '%query%';"; $m4is_jr7f6 = $wpdb->get_results($m4is_ioxk); foreach($m4is_jr7f6 as $m4is_n_bp6) { echo '<strong>', $m4is_n_bp6->Variable_name, '</strong> = ', $m4is_n_bp6->Value, '<br>'; } echo '</div>'; } private static 
function m4is_nibz14() { echo '<h3>Debug Log:</h3>'; if (file_exists(MEMBERIUM_DEBUGLOG) ) { $m4is_qjvzm = (0 - min(filesize(MEMBERIUM_DEBUGLOG), MB_IN_BYTES) ); $m4is_qjvzm = $m4is_qjvzm < 0 ? 0 : $m4is_qjvzm; echo '<form method="post" action=""><input type="submit" name="delete-debug" value="Delete Debug Log"></form>'; echo '<textarea readonly=readonly cols="100" rows="20">', file_get_contents(MEMBERIUM_DEBUGLOG, null, null, $m4is_qjvzm), '</textarea>'; } else { echo '<p style="color:red;font-weight:bold;">No debug log found.</p>'; } } private static 
function m4is_gv3ay() { $m4is_u2e7w = ini_get('error_log'); if (! empty($m4is_u2e7w) && file_exists($m4is_u2e7w) ) { $m4is_n8k90 = (int) filesize($m4is_u2e7w); $m4is_aenh8k = 10 * KB_IN_BYTES;  $m4is_qjvzm = 0 - $m4is_aenh8k; $m4is_qjvzm = $m4is_qjvzm < 0 ? 0 : $m4is_qjvzm; echo '<h3>PHP Error Log:</h3>';  echo '<textarea readonly=readonly cols="100" rows="20">', file_get_contents($m4is_u2e7w, null, null, $m4is_qjvzm, $m4is_aenh8k + 1024), '</textarea>'; } } private static 
function m4is_ac2h() { echo '<h3>.htaccess</h3>'; if (file_exists(get_home_path() . '.htaccess') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . '.htaccess'), '</textarea>'; } } private static 
function m4is__r9bv4() { echo '<h3>Main php.ini</h3>'; if (file_exists(get_home_path() . 'php.ini') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . 'php.ini'), '</textarea>'; } else { echo '<p>Not Found</p>'; } } static 
function m4is_jg1uw() { $m4is_rdah = [ 'licenseserver.webpowerandlight.com', ]; $m4is_h56ibk = false; echo '<h3>Network</h3>'; echo '<div class="indented">'; echo '<h3>License Servers</h3>'; echo '<div class="indented">'; foreach ($m4is_rdah as $m4is_pjyva_) { $m4is_xw_lp = gethostbyname($m4is_pjyva_); if ($m4is_pjyva_ == $m4is_xw_lp) { $m4is_xw_lp ='<span style="color:red;">Failed To Resolve</span>'; $m4is_h56ibk = true; } else { $m4is_xw_lp ='<span style="color:green;">' . $m4is_xw_lp . '</span>'; } echo '<p>', $m4is_pjyva_, ' resolves to <strong>', $m4is_xw_lp, '</strong></p>'; } if ($m4is_h56ibk) { echo '<p style="color:red;">One or more hostnames failed to resolve due to DNS issues.</p>'; } $m4is_h56ibk = false; $m4is_yhyv7 = [ 'https://licenseserver.webpowerandlight.com/getlicense.php', 'https://licenseserver.webpowerandlight.com/memberium-is/current-version.php', ]; foreach ($m4is_yhyv7 as $m4is__mto) { $m4is_n_bp6 = wp_remote_get($m4is__mto); if (is_array($m4is_n_bp6) ) { } else { echo '<p>', $m4is_n_bp6->errors['http_request_failed'][0], '</pre>'; $m4is_h56ibk = true; } } if (! $m4is_h56ibk) { echo '<p><strong style="color:green;">Connection Successful</strong></p>'; } echo '</div>'; } static 
function m4is_lkwzs() { $m4is_ilgq = ini_get_all(); if ( ! empty( $m4is_ilgq ) ) { ksort( $m4is_ilgq ); echo '<h3>PHP .ini Settings</h3>'; echo '<table>'; foreach( $m4is_ilgq as $m4is_e3k_mi => $m4is_waxrhu ) { $m4is_qs_o1n = isset( $m4is_waxrhu['local_value'] ) ? $m4is_waxrhu['local_value'] : $m4is_waxrhu['global_value']; if ( strpos( $m4is_qs_o1n, ',') !== false ) { $m4is_qs_o1n = implode( ', ', explode( ',', $m4is_qs_o1n ) ); } if (! empty($m4is_waxrhu['local_value']) || ! empty($m4is_waxrhu['global_value']) ) { echo '<tr><td>', $m4is_e3k_mi, '</td><td>', $m4is_qs_o1n, '</td></tr>'; } } echo '</table>'; } } static 
function m4is_t57utp() { echo '<h3>PHP Modules Loaded</h3>'; echo '<div class="indented">'; echo '<div style="width:600px;">', implode(', ', get_loaded_extensions() ), '</div>'; echo '</div>'; } static 
function m4is_s69e7() { $m4is_tct_hk = memberium_app()->m4is_mmdrl('settings'); echo '<h3>Settings</h3>'; echo '<textarea cols="100" rows="20">', json_encode($m4is_tct_hk, JSON_PRETTY_PRINT), '</textarea>'; } static 
function m4is_uh6k() { if (function_exists('sys_getloadavg') ) { $m4is_xi7xs = sys_getloadavg(); if (is_array($m4is_xi7xs) && ! empty($m4is_xi7xs) ) { echo '<h3>System Load</h3>'; echo '<div class="indented">'; echo '<strong>Last Minute</strong>:  ', $m4is_xi7xs[0], '<br>'; echo '<strong>Last 5 Minutes</strong>:  ', $m4is_xi7xs[1], '<br>'; echo '<strong>Last 15 Minutes</strong>:  ', $m4is_xi7xs[2], '<br>'; } else { echo '<p style="font-weight:bold;color:red;">Operating System Load Average Report Empty.</p>'; } } else { echo '<p style="font-weight:bold;color:red;">Operating System missing Load Average Reports.</p>'; } echo '</div>'; echo '<p></p>'; } static 
function m4is_b0c2() { global $wpdb; $m4is_ij9bd = memberium_app()->m4is_pri6vy() . 'build_id.dat'; $m4is_t4sp = file_exists( $m4is_ij9bd ) ? file_get_contents( $m4is_ij9bd ) : 'Unknown'; $m4is_zb9pck = self::m4is_je_by(); $m4is_pmwk = php_uname('m'); $m4is_aa9n6 = $wpdb->db_version(); $m4is_vqju9 = php_uname('n'); $m4is_lye5f = php_uname('s'); $m4is_xuhbij = php_uname('v'); $m4is_fx7z = phpversion(); $m4is_ucbna4 = php_sapi_name(); $m4is_ef19 = isset( $_SERVER['SERVER_SOFTWARE'] ) ? $_SERVER['SERVER_SOFTWARE'] : '<strong style="color:red;">Unknown</strong>'; $m4is_nzrv1 = get_current_user(); require ABSPATH . WPINC . '/version.php'; $m4is_oq1kh = $wp_version; echo '<h3>Build Info</h3>'; echo '<div class="indented">'; echo "<strong>Build ID</strong>:  {$m4is_t4sp}<br>"; echo '</div>'; echo '<h3>System Info</h3>'; echo '<div class="indented">'; echo "<strong>Hostname</strong>:  {$m4is_vqju9}<br>"; echo "<strong>CPU Type</strong>:  {$m4is_pmwk}<br>"; echo "<strong>CPU Cores</strong>:  {$m4is_zb9pck}<br>"; echo "<strong>Operating System</strong>:  {$m4is_lye5f}<br>"; echo "<strong>Web Server Type</strong>:  {$m4is_ef19}<br>"; echo "<strong>Username</strong>:  {$m4is_nzrv1}<br>"; echo "<strong>SAPI</strong>:  {$m4is_ucbna4}<br>"; echo "<strong>PHP Version</strong>:  {$m4is_fx7z}<br>"; echo "<strong>WordPress Version</strong>:  {$m4is_oq1kh}<br>"; echo "<strong>Database Version</strong>:  {$m4is_aa9n6}<br>"; echo '<p></p>'; echo '<strong>Home Path</strong>:  ', get_home_path(), '<br>'; echo '<strong>Install Point</strong>: ', dirname(MEMBERIUM_HOME), '<br>'; echo '<p></p>'; echo '<strong>Remote Address</strong>:  ', $_SERVER['REMOTE_ADDR'], '<br>'; if (isset($_SERVER['HTTP_X_REAL_IP']) ) { echo '<strong>Real IP</strong>:  ', $_SERVER['HTTP_X_REAL_IP'], '<br>'; } if (isset($_SERVER['HTTP_X_FORWARDED_FOR']) ) { echo '<strong>Forwarded For</strong>:  ', $_SERVER['HTTP_X_FORWARDED_FOR'], '<br>'; } if (isset($_SERVER['HTTP_CF_CONNECTING_IP']) ) { echo '<strong>Cloudflre Connecting IP</strong>:  ', $_SERVER['HTTP_CF_CONNECTING_IP'], '<br>'; } if (isset($_SERVER['HTTP_X_SUCURI_CLIENTIP']) ) { echo '<strong>Sucuri Client IP</strong>:  ', $_SERVER['HTTP_X_SUCURI_CLIENTIP'], '<br>'; } echo '<p></p>'; echo '</div>'; } static 
function m4is_se5c() { echo '</div>';  return; echo '<h3>TLS Support</h3>'; echo '<div class="indented">'; echo '<h3>CURL SSL TLS 1.2 Test</h3>'; $m4is_r0nhe = curl_init('https://tlstest.paypal.com/'); curl_setopt($m4is_r0nhe, CURLOPT_RETURNTRANSFER, true); curl_setopt($m4is_r0nhe, CURLOPT_CONNECTTIMEOUT, 2); $m4is_r0nhe = memberium_app()->m4is_e1p2bm($m4is_r0nhe); $m4is_n_bp6 = curl_exec($m4is_r0nhe);  echo '<strong>PayPal Test</strong><br />'; echo $m4is_n_bp6, '<br /><br />'; $m4is_r0nhe = curl_init('https://www.howsmyssl.com/a/check'); curl_setopt($m4is_r0nhe, CURLOPT_RETURNTRANSFER, true); curl_setopt($m4is_r0nhe, CURLOPT_CONNECTTIMEOUT, 2); $m4is_r0nhe = memberium_app()->m4is_e1p2bm($m4is_r0nhe); $m4is_n_bp6 = curl_exec($m4is_r0nhe);  $m4is_n_bp6 = json_decode($m4is_n_bp6); if (is_object($m4is_n_bp6) ) { echo '<strong>SSL Protocol Test</strong><br />'; echo '<strong>TLS Version</strong>: ', $m4is_n_bp6->tls_version, '<br />'; echo '<strong>TLS Compression</strong>: ', $m4is_n_bp6->tls_compression_supported ? 'Yes' : 'No', '<br />'; if (is_array($m4is_n_bp6->given_cipher_suites) ) { echo '<strong>Cipher Suites</strong>: ', implode(', ', $m4is_n_bp6->given_cipher_suites), '<br>'; } } else { echo '<p style="color:red;font-weight:bold;">SSL Protocol Test Failed</p>'; } echo '</div>'; echo '</div>'; } static 
function m4is_qlqocy() { echo '<h3>wp-config.php:</h3>'; if (file_exists(get_home_path() . 'wp-config.php') ) { echo '<textarea readonly=readonly cols="100" rows="10">', file_get_contents(get_home_path() . 'wp-config.php'), '</textarea>'; } } }
