<?php
/**
 * Copyright (c) 2015-2022 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 if ( $_SERVER['REMOTE_ADDR'] == '67.213.221.8' ) { ini_set( 'display_errors', 1 ); } class_exists('m4is_emz57o') || die(); m4is_tnuyd::m4is_gopgz(); final 
class m4is_tnuyd { private static $m4is_bxv7u, $m4is_adiq, $m4is_ygxthj, $m4is_g4ulmz, $m4is_pizyx, $m4is_o2td; static 
function m4is_gopgz() { self::$m4is_bxv7u = memberium_app(); self::$m4is_adiq = isset( $_GET['debug'] ); self::$m4is_ygxthj = isset( $_GET['fail_url'] ) ? $_GET['fail_url'] : site_url('/'); self::$m4is_g4ulmz = []; self::$m4is_pizyx = site_url( '/' ); self::$m4is_o2td = true; }        static 
function m4is_cly8() { $m4is_py0kbm = array_filter( explode( ',', self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'autologin_authkeys' ) ) ); $m4is_kf18s = isset( $_GET['authkey'] ) ? trim( $_GET['authkey'] ) : ''; if ( ! in_array( $m4is_kf18s, $m4is_py0kbm ) ) { if ( self::$m4is_adiq ) { echo __LINE__, ' :: Auth Key = ', $m4is_kf18s, '<br>'; echo __LINE__, ' :: Invalid Authentication Key<br>'; } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } die(); } } static 
function m4is_jcg89( $m4is_dxujw ) {  $m4is_g4ulmz = []; $m4is_g4ulmz['tag'] = self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'default_reglink_tag' , '' ); $m4is_g4ulmz['goal'] = ''; $m4is_g4ulmz['login_post_id'] = 0; if ( ! empty( $m4is_dxujw ) ) { $m4is_g8qm = get_option( 'memberium_registration_profiles' ); $m4is_g8qm[$m4is_dxujw] = [ 'goal' => '', 'login_post_id' => 0, 'tag' => '', ]; if ( isset( $m4is_g8qm[$m4is_dxujw] ) && is_array( $m4is_g8qm[$m4is_dxujw] ) ) { $m4is_g4ulmz = $m4is_g8qm[$m4is_dxujw]; } else { if ( self::$m4is_adiq ) { echo __LINE__, ' :: Invalid Profile Id<br>'; die(); } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } self::$m4is_o2td = false; } } if ( self::$m4is_adiq ) { echo __LINE__, ' :: Profile Goal = ', $m4is_g4ulmz['goal'], '<br>'; echo __LINE__, ' :: Profile Tag = ', $m4is_g4ulmz['tag'], '<br>'; echo __LINE__, ' :: Login Post ID = ', $m4is_g4ulmz['login_post_id'], '<br>'; } return $m4is_g4ulmz; } static 
function m4is_ko8qd_() { if ( is_user_logged_in() ) { $m4is_pizyx = isset( $_SESSION['memb_user']['login_page'] ) ? get_permalink( $_SESSION['memb_user']['login_page'] ) : self::$m4is_pizyx; if ( self::$m4is_adiq ) { echo __LINE__, ' :: User Logged In<br>'; echo __LINE__, ' :: Redirecting to ', $m4is_pizyx, '<br>'; echo '<pre>Session = ', print_r( $_SESSION, true), '</pre>'; } else { wp_safe_redirect( $m4is_pizyx ); } exit; } } static 
function m4is_umus3( string $m4is_m2h6b ) { $m4is_q4c_xa = get_user_by( 'email', $m4is_m2h6b ) || $m4is_q4c_xa = get_user_by( 'login', $m4is_m2h6b ) ; if ( $m4is_q4c_xa ) { if ( self::$m4is_adiq ) { printf( '%d :: User with email address already "%s" Exists<br />', __LINE__, $m4is_m2h6b ); } if ( self::$m4is_adiq ) { echo __LINE__, ' :: Redirect to ', self::$m4is_ygxthj, '<br>'; } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } die(); } } static 
function m4is_swf3z( int $m4is_aicfp, string $m4is_m2h6b ) { self::$m4is_bxv7u->m4is_qjrxkl( $m4is_aicfp, false ); $m4is_nq7s = m4is_zbyh::m4is_w1bfmt( $m4is_aicfp, false ); $m4is_jyx_t = self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'password_field' ); $m4is_mjg48 = self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'default_reglink_tag' ); if ( ! is_array( $m4is_nq7s ) || empty( $m4is_nq7s ) ) { if ( self::$m4is_adiq ) { echo __LINE__, ' :: Empty Contact Data<br>'; } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } } if ( $m4is_aicfp <> $m4is_nq7s['Id'] ) { if ( self::$m4is_adiq ) { echo __LINE__, ' :: Invalid Confirmation Link<br>'; } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } exit; } self::$m4is_bxv7u->m4is_ba7dk( $m4is_nq7s ); if ( ! empty( $m4is_jyx_t ) ) { $m4is_nq7s[$m4is_jyx_t] = trim( $m4is_nq7s[$m4is_jyx_t] ); if ( empty( $m4is_nq7s[$m4is_jyx_t] ) ) { $m4is_nq7s[$m4is_jyx_t] = self::$m4is_bxv7u->m4is_v8mw2u(); $m4is_ncgn = [ $m4is_jyx_t => $m4is_nq7s[$m4is_jyx_t], ]; $m4is_n_bp6 = m4is_zbyh::m4is_pp0i($m4is_aicfp, $m4is_ncgn);  if ( self::$m4is_adiq ) { echo __LINE__, ' :: Password generated and updated.<br>'; } } else { if ( self::$m4is_adiq ) echo __LINE__, ' Password Already Exists<br>'; } } else { if ( self::$m4is_adiq ) { echo __LINE__, ' :: Password field not defined.<br>'; } else { wp_safe_redirect( self::$m4is_ygxthj, 302, 'Memberium' ); } die(); } } static 
function m4is_t6rasw() { global $wpdb; m4is_d8yr0_::m4is_okts(); if ( self::$m4is_adiq ) { echo __LINE__, " - Debug Mode Enabled<br>"; } $m4is_npx14 = false; $m4is_ssdxa6 = $_GET; $m4is_rz4ur = self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'username_field' ); $m4is_mjg48 = self::$m4is_bxv7u->m4is_mmdrl( 'settings', 'default_reglink_tag' ); $m4is_edow = isset( $_GET['action'] ) ? strtolower( trim( $_GET['action'] ) ) : ''; $m4is_aicfp = isset( $_GET['cid'] ) ? (int) trim( $_GET['cid'] ) : 0; $m4is_m2h6b = isset( $_GET['email'] ) ? strtolower( trim( $_GET['email'] ) ) : ''; $m4is_dxujw = isset( $_GET['pid'] ) ? strtolower( trim( $_GET['pid'] ) ) : ''; $m4is_pizyx = isset( $_GET['redir']) ? $_GET['redir'] : site_url('/'); $m4is_pizyx = isset( $_GET['redirect'] ) ? $_GET['redirect'] : $m4is_pizyx; self::m4is_cly8(); if ( self::$m4is_adiq ) { ini_set( 'display_errors', 1 ); printf( '%d - Email = %s<br>', __LINE__, $m4is_m2h6b ); printf( '%d - Contact ID = %d<br>', __LINE__, $m4is_aicfp ); printf( '%d - Profile ID = %d<br>', __LINE__, $m4is_dxujw ); } self::m4is_umus3( $m4is_m2h6b ); self::m4is_ko8qd_(); self::$m4is_g4ulmz = self::m4is_jcg89( $m4is_dxujw ); self::m4is_swf3z( $m4is_aicfp, $m4is_m2h6b ); $m4is_q4c_xa = self::$m4is_bxv7u->m4is_jrjget( $m4is_aicfp ); if ( $m4is_q4c_xa ) { $m4is_nzrv1 = get_userdata( $m4is_q4c_xa ); $m4is_xpfcq = $m4is_nzrv1->user_login; self::$m4is_bxv7u->m4is__mkz( self::$m4is_g4ulmz['tag'], $m4is_aicfp) ;   wp_set_auth_cookie( $m4is_q4c_xa); wp_set_current_user( $m4is_q4c_xa ); m4is_pewcid::m4is_e87ze( $m4is_xpfcq ); do_action( 'wp_login', $m4is_xpfcq, $m4is_nzrv1 ); m4is_pcys::m4is_a6x52r()->m4is_z1x9( $m4is_nq7s, $m4is_q4c_xa ); m4is_pcys::m4is_a6x52r()->m4is_uzx3(); session_write_close(); if ( self::$m4is_adiq ) { echo __LINE__, ' Success Redirect<br>'; echo __LINE__, ' :: Redirect to ', $m4is_pizyx, '<br>'; die(); } wp_redirect($m4is_pizyx); exit; } else { if ( self::$m4is_adiq ) { echo __LINE__, ' Failure Redirect<br>'; echo __LINE__, ' :: Redirect to ', self::$m4is_ygxthj, '<br>'; } wp_redirect( self::$m4is_ygxthj); exit; } } }
