<?php
/**
 * Copyright (c) 2022 David J Bullock
 * Web Power and Light
 */

 class_exists( 'm4is_emz57o' ) || die(); 
class m4is_r4j7_m { static 
function m4is_a6x52r() : self { static $m4is_jprj8 = false; return $m4is_jprj8 ? $m4is_jprj8 : $m4is_jprj8 = new self; } private 
function __construct() { if ( is_admin() ) { add_filter( 'memberium/modules/active/names', [$this, 'm4is_a5tu'], 10, 1 ); } else { $this->m4is_ap508(); } if ( function_exists( 'oxygen_vsb_register_condition' ) ) { $this->m4is_kcur(); } } private 
function m4is_ap508() { add_action( 'wp', [$this, 'm4is_yq51'], 20 ); add_filter( 'do_shortcode_tag', [$this, 'm4is_dy6l9'], PHP_INT_MAX, 4 ); add_filter( 'memberium/modules/active/names', [$this, 'm4is_a5tu'], 10, 1 ); } 
function m4is_a5tu( array $m4is_its6y = []) { return array_merge( $m4is_its6y, ['Oxygen Block Builder for Memberium'] ); } 
function m4is_yq51() { $this->safe_tags = apply_filters( 'memberium/oxygen/tags', $this->safe_tags ); } 
function m4is_dy6l9( $m4is_k2qb08, $m4is_w9feq2, $m4is__nytb, $m4is_nhanw7 ) { $m4is_iweo5 = ( strpos( $m4is_w9feq2, 'ct_section' ) === 0 ); if ( ! $m4is_iweo5 && in_array( $m4is_w9feq2, $this->safe_tags ) ) { $m4is_iweo5 = true; } return $m4is_iweo5 ? do_shortcode( $m4is_k2qb08 ) : $m4is_k2qb08; } 
function m4is_kcur(){ $m4is_t_qmg = 'oxygen'; $m4is_flp3_b = m4is_l0uwos::m4is_a6x52r(); $m4is_eg2e = $m4is_flp3_b::PREFIX; $m4is_swhd5 = $m4is_flp3_b->m4is_lvmd()->m4is_vvsj( false, $m4is_t_qmg ); $m4is_yp8jv = $m4is_flp3_b->m4is_lvmd()->m4is_hos3p( $m4is_t_qmg ); $m4is_qmxu = $m4is_swhd5[ 'settings_title' ]; $m4is_m_465 = [ 'includes', "doesn't include", '==','!=' ]; $m4is_xcfsr = [ 'includes' ];  if( ! array_key_exists( 'memberships', $m4is_yp8jv ) ) { $m4is_fdf0v = $m4is_flp3_b->m4is_lvmd()->m4is_lc3g(); $m4is_fdf0v = isset( $m4is_fdf0v ) && is_array( $m4is_fdf0v ) ? $m4is_fdf0v : false; if ( $m4is_fdf0v ) { $this->any_membership_text = sprintf( __( "Any %s" ), $m4is_swhd5['membership_levels'], 'memberium' ); $m4is_rhfd = [ 'options' => [$this->any_membership_text] ]; foreach ( $m4is_fdf0v as $m4is_b40e_m => $m4is_tyoak ) { $m4is_rhfd['options'][$m4is_b40e_m] = stripslashes( $m4is_tyoak['name'] ) . "({$m4is_b40e_m})"; } $m4is_ho0w2 = $m4is_swhd5['membership_levels']; $m4is_owb4u = 'm4is_p1tx'; oxygen_vsb_register_condition( $m4is_ho0w2, $m4is_rhfd, $m4is_xcfsr, $m4is_owb4u, $m4is_qmxu ); } }  if( ! array_key_exists( 'tags1', $m4is_yp8jv ) ){ $m4is_c4fvo = memberium_app()->m4is_zuw6j4( [], $m4is_t_qmg ); if( ! empty( $m4is_c4fvo ) ){ $m4is_ho0w2 = sprintf( __( "Require %s", 'memberium' ), $m4is_swhd5['key_name'] ); $m4is_rhfd = [ 'options' => $m4is_c4fvo ]; $m4is_owb4u = 'm4is_o1r4'; oxygen_vsb_register_condition( $m4is_ho0w2, $m4is_rhfd, $m4is_m_465, $m4is_owb4u, $m4is_qmxu ); } }  if( ! array_key_exists( 'asset_id', $m4is_yp8jv ) ){ $m4is_ho0w2 = $m4is_swhd5['asset_id']; $m4is_owb4u = 'm4is_gs20a'; $this->conditions[$m4is_ho0w2] = "{$m4is_eg2e}_asset_id"; $m4is_rhfd = ['custom' => true]; oxygen_vsb_register_condition($m4is_ho0w2, $m4is_rhfd, $m4is_xcfsr, $m4is_owb4u, $m4is_qmxu); } }  
function m4is_z_1tf8( $m4is_i2zk ) { $m4is_p78sgz = [ 'any_membership' => 0, 'asset_id' => '', 'contact_ids' => '', 'eval' => '', 'invert_results' => 0, 'logged_in_only' => 0, 'logged_out_only' => 0, 'memberships' => '', 'tags1' => '', 'tags2' => '' ]; $m4is_hxkw6 = wp_parse_args( $m4is_i2zk, $m4is_p78sgz ); return m4is_l0uwos::m4is_a6x52r()->m4is_dm0y8e()->m4is_tzv4o( $m4is_hxkw6, 'oxygen' ); }  
function m4is_vm_n( $m4is_rhfd ){ $m4is_i2zk = explode( '(', $m4is_rhfd ); return (int) end( $m4is_i2zk ); } private $safe_tags = [ 'ct_code_block', 'ct_headlines', 'ct_link_button', 'ct_link', 'ct_text_block', 'oxy_rich_text', ]; public $any_membership_text;  }  
function m4is_p1tx($m4is_rhfd, $m4is_xcfsr){ $m4is_yude6m = m4is_r4j7_m::m4is_a6x52r(); $m4is_tct_hk = []; $m4is_p74ya = $m4is_yude6m->any_membership_text; if( $m4is_rhfd === $m4is_p74ya ){ $m4is_tct_hk['any_membership'] = 1; } else { $m4is_tct_hk['memberships'] = $m4is_yude6m->m4is_vm_n($m4is_rhfd); } return $m4is_yude6m->m4is_z_1tf8($m4is_tct_hk); } 
function m4is_o1r4($m4is_rhfd, $m4is_xcfsr) { $m4is_yude6m = m4is_r4j7_m::m4is_a6x52r(); $m4is_svfj = in_array($m4is_xcfsr, ['!=', "doesn't include"]) ? '-' : ''; $m4is_b40e_m = $m4is_yude6m->m4is_vm_n($m4is_rhfd); $m4is_tct_hk = ['tags1' => $m4is_svfj . $m4is_b40e_m]; return $m4is_yude6m->m4is_z_1tf8($m4is_tct_hk); } 
function m4is_gs20a($m4is_rhfd, $m4is_xcfsr) {  if( ! empty($m4is_rhfd) ){ $m4is_rhfd = str_replace([" ", "-", "\n", "\r", "\t"], '', $m4is_rhfd); }  if( ! empty($m4is_rhfd) ){ $settings = ['asset_id' => $m4is_rhfd]; return m4is_r4j7_m::m4is_a6x52r()->m4is_z_1tf8($settings); } else { return true; } }
