<?php
/**
 * Copyright (c) 2018-2022 David J Bullock
 * Web Power and Light
*/

 class_exists('m4is_emz57o') || die();  
class m4is_qcoj { public $slug = 'divi';  public $script_version = '1.0.7';  public $to_json = [];  public $omitted_blocks = [];  public $ns = '';  public $prefix = '';  public $I18n = '';  public $access_class;  static 
function m4is_a6x52r() : self { static $m4is_jprj8; return isset( $m4is_jprj8 ) ? $m4is_jprj8 : $m4is_jprj8 = new self(); } private 
function __construct() { $this->access_class = m4is_l0uwos::m4is_a6x52r(); $this->prefix = $this->access_class::PREFIX; $this->ns = $this->access_class::NS; } 
function m4is_gopgz() { add_filter( "{$this->ns}/{$this->slug}/control/config", [$this, 'm4is_d02r95'], 10, 1 ); $m4is_bkujny = $this->access_class->m4is_lvmd(); $this->I18n = $m4is_bkujny->m4is_vvsj( false, $this->slug ); $this->to_json['WPAL_BLOCKS_SETTINGS_TITLE'] = $this->I18n['settings_title']; $this->to_json['WPAL_BLOCKS_PREFIX'] = $this->prefix; $this->to_json['WPAL_BLOCKS_KEYS_REMOVED_TEXT'] = $this->I18n['keys_removed_text']; $this->to_json['tags'] = $m4is_bkujny->m4is_ee0h();  $this->to_json['controls'] = $m4is_bkujny->m4is_ubq5l( $this->slug );  $this->omitted_blocks = apply_filters( "{$this->ns}/{$this->slug}/settings/omitted_blocks", ['et_pb_column', 'et_pb_column_inner'] );  add_action('et_builder_ready', [$this, 'm4is_tveor'], 9999 );  add_action(is_admin() ? 'admin_enqueue_scripts' : 'wp_enqueue_scripts', [$this, 'm4is_zqb0xf'], 9999);  }  
function m4is_tveor(){ global $shortcode_tags; $m4is_u27ay = []; foreach ( $shortcode_tags as $m4is_w9feq2 => $m4is_i0e3 ) { if ( is_array( $m4is_i0e3 ) ) { if ( $m4is_i0e3[0] instanceof ET_Builder_Element || $m4is_i0e3[0] instanceof ET_Builder_Module ) { $m4is_u27ay[$m4is_w9feq2] = $m4is_i0e3; remove_shortcode($m4is_w9feq2, $m4is_i0e3); } } } if ( !empty($m4is_u27ay) ){ foreach ( $m4is_u27ay as $m4is_w9feq2 => $m4is_i0e3 ) { $m4is_ycymv = $m4is_i0e3[0]; $m4is_gdnxz3 = $m4is_i0e3[1]; $m4is_ycymv->settings_modal_toggles['custom_css']['toggles']['wpal-blocks'] = ['title' => $this->I18n['settings_title'], 'priority' => 100]; if ( !isset($m4is_ycymv->fields_unprocessed["{$this->prefix}_anymembership"] ) ){ $m4is_jijt = in_array($m4is_w9feq2, $this->omitted_blocks) ? [] : $this->to_json['controls']; if ( is_array($m4is_jijt) && !empty($m4is_jijt) ){ $m4is_ycymv->fields_unprocessed = array_merge($m4is_ycymv->fields_unprocessed, $m4is_jijt); } } add_shortcode( $m4is_w9feq2, function($m4is_qvehs, $m4is_amunwi, $m4is_hlxs74) use ($m4is_ycymv, $m4is_gdnxz3) { return $m4is_ycymv->$m4is_gdnxz3( $m4is_qvehs, $m4is_amunwi, $m4is_hlxs74 ); }); } } }  
function m4is_d02r95( array $m4is_iikfu ) : array { $m4is_rjuf = []; if ( is_array($m4is_iikfu) && !empty($m4is_iikfu) ){ foreach( $m4is_iikfu as $m4is_celntz => $m4is_tenvhx ) { $m4is_j1vz = !empty($m4is_tenvhx['type']) ? $m4is_tenvhx['type'] : false; $m4is_ho0w2 = !empty($m4is_tenvhx['name']) ? $m4is_tenvhx['name'] : false; $m4is_yxrwc = !empty($m4is_tenvhx['description']) ? $m4is_tenvhx['description'] : false; $m4is_vr3h8 = !empty($m4is_tenvhx['sanitize']) ? $m4is_tenvhx['sanitize'] : false; if ( $m4is_j1vz && $m4is_ho0w2 ){ switch ($m4is_j1vz) { case 'checkbox': $m4is_rjuf[$m4is_ho0w2] = [ 'wpald' => 'toggle', 'wpald_level' => empty( $m4is_tenvhx['level'] ) ? '' : $m4is_tenvhx['level'], 'wpald_toggles' => isset( $m4is_tenvhx['toggles'] ) && is_array( $m4is_tenvhx['toggles'] ) ? $m4is_tenvhx['toggles'] : false, 'type' => 'yes_no_button', 'label' => $m4is_tenvhx['label'], 'default' => isset( $m4is_tenvhx['default'] ) && (int) $m4is_tenvhx['default'] > 0 ? 'on' : 'off', 'options' => [ 'off' => empty( $m4is_tenvhx['label_off']) ? _x( 'Off', 'divi', $this->ns ) : $m4is_tenvhx['label_off'], 'on' => empty( $m4is_tenvhx['label_on'] ) ? _x('On', 'divi', $this->ns ) : $m4is_tenvhx['label_on'], ], ]; break; case 'textarea': $m4is_rjuf[$m4is_ho0w2] = [ 'wpald' => 'textarea', 'type' => 'text', 'label' => $m4is_tenvhx['label'], 'default' => '' ]; break; case 'text': $m4is_rjuf[$m4is_ho0w2] = [ 'wpald' => 'text', 'type' => 'text', 'label' => $m4is_tenvhx['label'], 'default' => '' ]; break; case 'SELECT2': $m4is_rjuf[$m4is_ho0w2] = [ 'wpald' => 'select2', 'type' => 'text', 'label' => $m4is_tenvhx['label'] ]; break; default: break; } if ( $m4is_yxrwc ){ $m4is_rjuf[$m4is_ho0w2]['description'] = $m4is_yxrwc; } if ( $m4is_vr3h8 ){ $m4is_rjuf[$m4is_ho0w2]['sanitize'] = $m4is_vr3h8; } $m4is_rjuf[$m4is_ho0w2]['additional_att'] = empty($m4is_tenvhx['additional_att']) ? $m4is_ho0w2 : $m4is_tenvhx['additional_att']; $m4is_rjuf[$m4is_ho0w2]['option_category'] = empty($m4is_tenvhx['option_category']) ? 'configuration' : $m4is_tenvhx['option_category']; $m4is_rjuf[$m4is_ho0w2]['tab_slug'] = empty($m4is_tenvhx['tab_slug']) ? 'custom_css' : $m4is_tenvhx['tab_slug'] ; $m4is_rjuf[$m4is_ho0w2]['toggle_slug'] = empty($m4is_tenvhx['toggle_slug']) ? 'wpal-blocks' : $m4is_tenvhx['toggle_slug'] ; } } } return $m4is_rjuf; }  
function m4is_zqb0xf(){ $m4is_hdsl31 = 'wpal-blocks-divi-editor'; $m4is_bguci9 = plugin_dir_url( __FILE__ ); $m4is_exu5 = $m4is_hdsl31 . '_main'; $m4is_bg21l = 'select2css_divi'; $this->access_class->m4is_lvmd()->m4is_x8mgkb( false, $m4is_hdsl31 ); wp_register_style( $m4is_bg21l, $m4is_bguci9 . 'select2_divi.css', false, $this->script_version, 'all' ); wp_register_script( $m4is_exu5, $m4is_bguci9 . 'editor.js', ['jquery'], $this->script_version, true) ; wp_enqueue_style( $m4is_bg21l ); wp_enqueue_script( "{$m4is_hdsl31}_s2js" ); wp_enqueue_script( $m4is_exu5 ); wp_localize_script( $m4is_exu5, 'wpald_params', $this->to_json ); } }
