<?php
/**
 * Copyright (c) 2017-2022 David J Bullock
 * Web Power and Light
 */

 class_exists('m4is_emz57o') || die(); final 
class m4is_jy6kn4 { private $m4is_u152_0 = [ 'active', 'completed', 'pending-cancel', 'processing', ], $m4is_znk5 = [ 'cancelled', 'expired',  ], $m4is_vh7i = [ 'pending', 'on-hold', ], $m4is_n0ajf = [ 'account_first_name' => 'FirstName', 'account_last_name' => 'LastName', 'first_name' => 'FirstName', 'last_name' => 'LastName', 'billing_address_1' => 'StreetAddress1', 'billing_address_2' => 'StreetAddress2', 'billing_city' => 'City', 'billing_company' => 'Company', 'billing_country' => 'Country', 'billing_email' => 'Email', 'billing_phone' => 'Phone1', 'billing_postcode' => 'PostalCode', 'billing_state' => 'State', 'shipping_address_1' => 'Address2Street1', 'shipping_address_2' => 'Address2Street2', 'shipping_city' => 'City2', 'shipping_country' => 'Country2', 'shipping_email' => 'Email2', 'shipping_phone' => 'Phone2', 'shipping_postcode' => 'PostalCode2', 'shipping_state' => 'State2', ]; public $post_keys = [ 'canc' => '_memberium_canc_tag', 'main' => '_memberium_main_tag', 'payf' => '_memberium_payf_tag', 'susp' => '_memberium_susp_tag', ];  static 
function m4is_a6x52r() : self { static $m4is_jprj8 = false; return $m4is_jprj8 ? $m4is_jprj8 : $m4is_jprj8 = new self; } private 
function __construct() { $this->m4is_ap508(); $this->m4is_u152_0 = wc_get_is_paid_statuses(); if (is_admin() ) { require_once __DIR__ . '/admin.php'; m4is_g2kca::m4is_a6x52r(); } else { require_once __DIR__ . '/frontend.php'; m4is_bsv1::m4is_a6x52r(); } } private 
function m4is_ap508() { add_action( 'woocommerce_order_status_changed', [$this, 'm4is_x6v2x'], 10, 3 ); add_action( 'woocommerce_subscription_status_updated', [$this, 'm4is_krle'], 10, 3 ); add_filter( 'memberium/registration/field_map', [$this, 'm4is_tyhn19'], 10, 1 ); add_filter( 'memberium/usermeta/crm_field_maps', [$this, 'm4is_tyhn19'], 10, 1 ); add_filter( 'memberium/usermeta/transmute', [$this, 'm4is_vg46f_'], 10, 3 ); add_filter( 'woocommerce_new_customer_data', [$this, 'm4is__19jgv'], 10 ); } 
function m4is_x6v2x( $m4is_cmat, $m4is_bd4j, $m4is_ytwk3 ) { $m4is_rprd_t = wc_get_order( $m4is_cmat ); $m4is_q4c_xa = $m4is_rprd_t->get_user_id(); if ( ! $m4is_q4c_xa ) { return; } $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); if (! $m4is_aicfp) { return; } $m4is_cesjr = $m4is_rprd_t->get_items(); if (is_array($m4is_cesjr) && ! empty($m4is_cesjr) ) { foreach ($m4is_cesjr as $item_key => $m4is_u7wr1f ) { $m4is_sdob0 = $m4is_u7wr1f->get_product_id(); $this->m4is_apx0b( $m4is_aicfp, $m4is_q4c_xa, $m4is_sdob0, $m4is_cmat, $m4is_ytwk3, $m4is_bd4j ); } } } private 
function m4is_u6zwhr( $m4is__xysg = 0, $m4is_q4c_xa = 0, $m4is_yeag = '' ) { $m4is__xysg = (int) $m4is__xysg; $m4is_q4c_xa = (int) $m4is_q4c_xa; if ( empty( $m4is__xysg ) || empty( $m4is_q4c_xa ) || empty( $m4is_yeag ) ) { return; } if ( $m4is_q4c_xa ) { $m4is_nzrv1 = get_user_by( 'id', $m4is_q4c_xa ); $m4is_q4c_xa = $m4is_nzrv1->ID; $m4is_xpfcq = $m4is_nzrv1->user_login; $m4is_ijvi = $m4is_nzrv1->user_email; } else { $m4is_q4c_xa = 0; $m4is_xpfcq = 'Memberium'; $m4is_ijvi = ''; } $m4is_q1oc = [ 'comment_agent' => 'Memberium', 'comment_approved' => 1, 'comment_author_email' => $m4is_ijvi, 'comment_author_IP' => '', 'comment_author_url' => '', 'comment_author' => $m4is_xpfcq, 'comment_content' => trim( $m4is_yeag ), 'comment_date' => current_time( 'mysql' ), 'comment_parent' => 0, 'comment_post_ID' => (int) $m4is__xysg, 'comment_type' => 'order_note', 'user_id' => $m4is_q4c_xa, ]; wp_insert_comment( $m4is_q1oc ); } private 
function m4is_apx0b( $m4is_aicfp, $m4is_q4c_xa, $m4is_sdob0, $m4is_cmat, $m4is_rr90, $m4is_bd4j ) { $m4is_aicfp = (int) $m4is_aicfp; $m4is_q4c_xa = (int) $m4is_q4c_xa; $m4is_sdob0 = (int) $m4is_sdob0; $m4is_cmat = (int) $m4is_cmat; $m4is_rr90 = (string) $m4is_rr90; $m4is_bd4j = (string) $m4is_bd4j; if ($m4is_rr90 <> $m4is_bd4j) { if ($m4is_aicfp && $m4is_sdob0) { $m4is_znf9 = $this->m4is_ahjv_($m4is_sdob0); $m4is__yib_ = ''; $m4is_eg2e = 'Memberium '; $m4is_f39_it = in_array($m4is_bd4j, $this->m4is_u152_0); if (in_array($m4is_rr90, $this->m4is_u152_0) ) { if ($m4is_znf9['main']) { memberium_app()->m4is__mkz($m4is_znf9['main'], $m4is_aicfp); $m4is__yib_ .= "{$m4is_eg2e} added tag {$m4is_znf9['main']}<br>"; }  if ($m4is_znf9['canc']) { memberium_app()->m4is__mkz(-abs($m4is_znf9['canc']), $m4is_aicfp); $m4is__yib_ .= "{$m4is_eg2e} removed tag {$m4is_znf9['canc']}<br>"; } if ($m4is_znf9['payf']) { memberium_app()->m4is__mkz(-abs($m4is_znf9['payf']), $m4is_aicfp); $m4is__yib_ .= "{$m4is_eg2e} removed tag {$m4is_znf9['payf']}<br>"; }  if ($m4is_znf9['susp']) { memberium_app()->m4is__mkz(-abs($m4is_znf9['susp']), $m4is_aicfp); $m4is__yib_ .= "{$m4is_eg2e} removed tag {$m4is_znf9['susp']}<br>"; } } elseif ($m4is_rr90 == 'failed') { memberium_app()->m4is__mkz($m4is_znf9['payf'], $m4is_aicfp); if ($m4is_znf9['main']) $m4is__yib_ .= "{$m4is_eg2e} added tag {$m4is_znf9['payf']}<br>"; } elseif ( in_array($m4is_rr90, $this->m4is_znk5) ) { memberium_app()->m4is__mkz($m4is_znf9['canc'], $m4is_aicfp); if ($m4is_znf9['main']) $m4is__yib_ .= "{$m4is_eg2e} added tag {$m4is_znf9['canc']}<br>"; } elseif ($m4is_rr90 == 'expired') { memberium_app()->m4is__mkz(0 - $m4is_znf9['main'], $m4is_aicfp); if ($m4is_znf9['main']) $m4is__yib_ .= "{$m4is_eg2e} removed tag {$m4is_znf9['main']}<br>"; } elseif ($m4is_rr90 == 'on-hold') { memberium_app()->m4is__mkz($m4is_znf9['susp'], $m4is_aicfp); if ($m4is_znf9['main']) $m4is__yib_ .= "{$m4is_eg2e} added tag {$m4is_znf9['susp']}<br>"; } $this->m4is_u6zwhr($m4is_cmat, $m4is_q4c_xa, $m4is__yib_); } } } private 
function m4is_c_g3( int $m4is_q4c_xa, int $m4is_sdob0, int $m4is_x8mdil ) : bool { $m4is_q4c_xa = (int) $m4is_q4c_xa; $m4is_sdob0 = (int) $m4is_sdob0; $m4is_x8mdil = (int) $m4is_x8mdil; $m4is_w5ky4q = [ 'subscriptions_per_page' => -1, 'customer_id' => $m4is_q4c_xa, 'product_id' => $m4is_sdob0, 'subscription_status' => $this->m4is_u152_0, ]; $m4is_uke5g = wcs_get_subscriptions( $m4is_w5ky4q ); unset( $m4is_uke5g[$m4is_x8mdil] ); return (bool) count($m4is_uke5g); }  
function m4is_mszk( int $m4is_q4c_xa, int $m4is_sdob0, int $m4is_dlw7o ) : bool { $m4is_w5ky4q = [ 'customer_id' => $m4is_q4c_xa, 'return' => 'ids', 'status' => $this->m4is_u152_0, 'product_id' => $m4is_sdob0, ]; $m4is_ggt68 = wc_get_orders( $m4is_w5ky4q );  $m4is_ggt68 = array_diff( $m4is_ggt68, [ $m4is_dlw7o ]); foreach( $m4is_ggt68 as $m4is_cmat ) { $m4is_rprd_t = wc_get_order( $m4is_cmat ); $m4is_cesjr = $m4is_rprd_t->get_items(); foreach( $m4is_cesjr as $m4is_u7wr1f ) { if ( $m4is_u7wr1f->get_product_id() == $m4is_sdob0 ) { return true; } } } return false; }  
function m4is_d9rqc() { return $this->post_keys; } 
function m4is_ahjv_($m4is_sdob0) { $m4is_galwv0 = get_post_meta($m4is_sdob0); $m4is_znf9 = []; if (is_array($m4is_galwv0) ) { foreach($this->post_keys as $m4is_ho0w2 => $m4is_ap3_) { $m4is_znf9[$m4is_ho0w2] = empty($m4is_galwv0[$m4is_ap3_][0]) ? 0 : $m4is_galwv0[$m4is_ap3_][0]; } } return $m4is_znf9; }   
function m4is__19jgv($m4is_r_sa8) { if (empty($m4is_r_sa8['user_pass']) ) { $m4is_r_sa8['user_pass'] = memberium_app()->m4is_v8mw2u(); } if (isset($_POST['account_first_name']) && ! empty($_POST['account_first_name'])) { $m4is_r_sa8['first_name'] = trim($_POST['account_first_name']); } if (isset($_POST['account_last_name']) && ! empty($_POST['account_last_name'])) { $m4is_r_sa8['last_name'] = trim($_POST['account_last_name']); } if (get_option('woocommerce_registration_generate_username') !== 'no') { if (! username_exists($m4is_r_sa8['user_email']) ) { $m4is_r_sa8['user_login'] = $m4is_r_sa8['user_email']; } } return $m4is_r_sa8; } 
function m4is_krle($m4is_ie4p50, $m4is_ytwk3, $m4is_bd4j) { $m4is_jc9gya = $m4is_ie4p50->get_id(); $m4is_q4c_xa = $m4is_ie4p50->get_user_id(); if (! $m4is_q4c_xa) { $this->m4is_u6zwhr($m4is_jc9gya, 0, 'Memberium skipped applying tags due to no assigned WordPress user.'); return; } $m4is_aicfp = m4is_zbyh::m4is_fhxr6( $m4is_q4c_xa ); if (! $m4is_aicfp) { $this->m4is_u6zwhr($m4is_jc9gya, $m4is_q4c_xa, 'Memberium skipped applying tags due to no assigned CRM contact.'); return; } $m4is_cesjr = $m4is_ie4p50->get_items(); if (is_array($m4is_cesjr) && ! empty($m4is_cesjr) ) { foreach($m4is_cesjr as $m4is_amh9 => $m4is_u7wr1f) { $m4is_sdob0 = $m4is_u7wr1f->get_product_id(); if (! in_array($m4is_ytwk3, $this->m4is_u152_0) ) { $m4is_h20k9 = $this->m4is_c_g3($m4is_q4c_xa, $m4is_sdob0, $m4is_jc9gya); if ($m4is_h20k9) { $this->m4is_u6zwhr($m4is_jc9gya, $m4is_q4c_xa, 'Memberium skipped applying deactivation tag due to other active subscriptions.'); break; } } $this->m4is_apx0b($m4is_aicfp, $m4is_q4c_xa, $m4is_sdob0, $m4is_ie4p50->id, $m4is_ytwk3, $m4is_bd4j); } } } 
function m4is_tyhn19( array $m4is_xeguxz ) : array { return array_merge( $m4is_xeguxz, $this->m4is_n0ajf ); } 
function m4is_ij_9n($m4is_rhfd, $m4is_sv3h, $m4is_aicfp = 0) { return $m4is_rhfd; } 
function m4is_vg46f_($m4is_rhfd, $m4is_sv3h, $m4is_aicfp = 0) { if (in_array($m4is_sv3h, ['Country', 'Country2', 'Country3'])) { if (strlen($m4is_rhfd) < 4) { $m4is_rhfd = m4is_bjx91g::m4is_a5y9f($m4is_rhfd); } } elseif (in_array($m4is_sv3h, ['PostalCode', 'PostalCode2', 'PostalCode3'])) { $m4is_rhfd = strtoupper($m4is_rhfd); } return trim($m4is_rhfd); }  }
