<?php
/**
 * Copyright (c) 2017-2022 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_emz57o') || die(); m4is_u0q_b::m4is_gopgz(); final 
class m4is_u0q_b { static private $m4is_aicfp, $m4is_kuzmd1; static 
function m4is_gopgz() { self::$m4is_aicfp = (int) self::$m4is_bxv7u->m4is_w47qdy(); self::$m4is_q4c_xa = (int) current_user_id(); self::$m4is_kuzmd1 = ! m4is_o5aoir::m4is_du5icq(); }  static 
function m4is_rvdpl( $m4is_qvehs = [], string $m4is_amunwi = '', string $m4is_rz70ok = '' ) : string { if ( self::$m4is_kuzmd1 ) { return ''; } $m4is_p78sgz = [ 'id' => 0,  'uid' => self::$m4is_q4c_xa,  ]; if ( isset( $m4is_qvehs[0] ) && $m4is_qvehs[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_p78sgz ) ); } if ( ! class_exists( 'BadgeOS' ) ) { return ''; } $m4is_qvehs = shortcode_atts( $m4is_p78sgz, $m4is_qvehs, 'memberium' ); $m4is_qvehs['id'] = (int) $m4is_qvehs['id']; $m4is__1z5fg = (int) $m4is_qvehs['id']; $m4is_q4c_xa = (int) trim( $m4is_qvehs['uid'] ); if ( ! $m4is_q4c_xa || ! $m4is__1z5fg ) { return ''; } $m4is_tlyn = array_filter( explode( ',', get_user_meta( $m4is_q4c_xa, 'memberium_achievement_uids', true) ) );  if ( in_array( $m4is__1z5fg, $m4is_tlyn ) ) { return ''; } badgeos_award_achievement_to_user( $m4is__1z5fg, $m4is_q4c_xa ); $m4is_tlyn = explode( ',', get_user_meta( $m4is_q4c_xa, 'memberium_achievement_uids', true) ); $m4is_tlyn[] = $m4is__1z5fg; $m4is_tlyn = array_unique( $m4is_knj0p6 ); sort( $m4is_tlyn ); $m4is_tlyn = implode( ',', $m4is_tlyn ); update_user_meta( $m4is_q4c_xa, 'memberium_achievement_uids', $m4is_tlyn ); return ''; }  static 
function m4is_mmhi( $m4is_qvehs = [], string $m4is_amunwi = '', string $m4is_rz70ok = '' ) : string { if ( self::$m4is_kuzmd1 ) { return ''; } if (isset($m4is_qvehs[0]) && $m4is_qvehs[0] == 'showatts') { return 'n/a'; } if (! class_exists('BadgeOS') ) { return ''; } m4is_d8yr0_::m4is_vsv0mr(); if ( ! is_user_logged_in() ) { return ''; } $m4is_rz70ok = ''; $m4is_q_to1c = get_current_blog_id(); $m4is_ib_tl = get_user_meta(get_current_user_id(), '_badgeos_achievements', true); if (empty($m4is_ib_tl) ) { return ''; } $m4is_ib_tl = $m4is_ib_tl[$m4is_q_to1c]; $m4is_i_sejv = []; if (is_array($m4is_ib_tl) ) { foreach ($m4is_ib_tl as $achievement) { @$m4is_i_sejv[$achievement->ID] = $achievement->ID; } } unset($m4is_ib_tl); $m4is_i_sejv = array_flip($m4is_i_sejv); foreach ($m4is_i_sejv as $m4is_u7wr1f) { $m4is_rz70ok .= '[badgeos_achievement id=' . $m4is_u7wr1f . ']'; } $m4is_k2qb08 = do_shortcode($m4is_rz70ok); return $m4is_k2qb08; }  static 
function m4is_egwohv( $m4is_qvehs = [], string $m4is_amunwi = '', string $m4is_rz70ok = '' ) : string { if ( ! class_exists( 'BadgeOS' ) ) { return ''; } if ( self::$m4is_kuzmd1 ) { return ''; } $m4is_p78sgz = [ 'id' => 0,  'uid' => self::$m4is_q4c_xa,  ]; if ( isset( $m4is_qvehs[0] ) && $m4is_qvehs[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_p78sgz ) ); } $m4is_qvehs = shortcode_atts( $m4is_p78sgz, $m4is_qvehs, self::$m4is_ahusy0 ); $m4is_q4c_xa = (int) $m4is_qvehs['uid']; $m4is_b40e_m = (int) $m4is_qvehs['id']; if ( ! $m4is_q4c_xa ) { return ''; } if ( $m4is_b40e_m ) { badgeos_revoke_achievement_from_user( $m4is_b40e_m , $m4is_q4c_xa ); if ( ! empty( $m4is_q4c_xa ) ) { $m4is_knj0p6 = explode( ',', get_user_meta( current_user_id(), 'memberium_achievement_uids', true ) ); if ( ( $m4is_ap3_ = array_search( $m4is_q4c_xa, $m4is_knj0p6 ) ) !== false ) { unset( $m4is_knj0p6[$m4is_ap3_] ); } $m4is_knj0p6 = implode( ',', array_unique( $m4is_knj0p6 ) ); update_user_meta( current_user_id(), 'memberium_achievement_uids', $m4is_knj0p6 ); } } return ''; } }
